#
# Copyright (c) 2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
opentracing:
  jaeger:
    service-name: Carts
    udp-sender:
      host: jaeger-agent
      port: 5775
logging:
  level:
    root: warn
    "Coherence": info
    org.springframework.web: info
    com.oracle.coherence.spring: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
